version: '3.8'

# Development override for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  # Backend API - Development mode
  backend:
    build:
      context: .
      target: base
    command: pnpm run dev:backend
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGODB_URI: mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-password123}@mongodb:27017/${MONGO_DB_NAME:-grs_delivery}?authSource=admin
      REDIS_URL: redis://:${REDIS_PASSWORD:-redis123}@redis:6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redis123}
      JWT_SECRET: ${JWT_SECRET:-dev-jwt-secret-key}
      CORS_ORIGIN: http://localhost:3001,http://localhost:3002,http://localhost:3003,http://localhost:3004

  # Public PWA - Development mode
  public-pwa:
    build:
      context: .
      target: base
    command: pnpm run dev:public
    volumes:
      - ./packages/public-pwa:/app/packages/public-pwa
      - /app/packages/public-pwa/node_modules
      - /app/packages/public-pwa/.next
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3000
      NEXT_PUBLIC_WS_URL: ws://localhost:3000

  # Admin PWA - Development mode
  admin-pwa:
    build:
      context: .
      target: base
    command: pnpm run dev:admin
    volumes:
      - ./packages/admin-pwa:/app/packages/admin-pwa
      - /app/packages/admin-pwa/node_modules
      - /app/packages/admin-pwa/.next
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3000
      NEXT_PUBLIC_WS_URL: ws://localhost:3000

  # Business PWA - Development mode
  business-pwa:
    build:
      context: .
      target: base
    command: pnpm run dev:business
    volumes:
      - ./packages/business-pwa:/app/packages/business-pwa
      - /app/packages/business-pwa/node_modules
      - /app/packages/business-pwa/.next
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3000
      NEXT_PUBLIC_WS_URL: ws://localhost:3000

  # Driver PWA - Development mode
  driver-pwa:
    build:
      context: .
      target: base
    command: pnpm run dev:driver
    volumes:
      - ./packages/driver-pwa:/app/packages/driver-pwa
      - /app/packages/driver-pwa/node_modules
      - /app/packages/driver-pwa/.next
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3000
      NEXT_PUBLIC_WS_URL: ws://localhost:3000

  # Remove nginx in development (use direct ports)
  nginx:
    profiles:
      - production