version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: grs-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password123}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME:-grs_delivery}
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - grs-network

  # Redis Cache
  redis:
    image: redis:7.2-alpine
    container_name: grs-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis123}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - grs-network

  # Build the single image
  app:
    build:
      context: .
      dockerfile: Dockerfile.simple
      args:
        PNPM_FLAGS: --no-frozen-lockfile
    image: delivery-system-app

  # Backend API
  backend:
    extends: app
    container_name: grs-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      SERVICE_NAME: backend
      PORT: 3000
      MONGODB_URI: mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-password123}@mongodb:27017/${MONGO_DB_NAME:-grs_delivery}?authSource=admin
      REDIS_URL: redis://:${REDIS_PASSWORD:-redis123}@redis:6379
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-this}
      CORS_ORIGIN: https://grsdeliver.com,https://admin.grsdeliver.com,https://business.grsdeliver.com,https://driver.grsdeliver.com
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    networks:
      - grs-network

  # Public PWA
  public-pwa:
    extends: app
    container_name: grs-public-pwa
    restart: unless-stopped
    environment:
      NODE_ENV: production
      SERVICE_NAME: public-pwa
      NEXT_PUBLIC_API_URL: https://api.grsdeliver.com
      NEXT_PUBLIC_WS_URL: wss://api.grsdeliver.com
    ports:
      - "3001:3001"
    depends_on:
      - backend
    networks:
      - grs-network

  # Admin PWA
  admin-pwa:
    extends: app
    container_name: grs-admin-pwa
    restart: unless-stopped
    environment:
      NODE_ENV: production
      SERVICE_NAME: admin-pwa
      NEXT_PUBLIC_API_URL: https://api.grsdeliver.com
      NEXT_PUBLIC_WS_URL: wss://api.grsdeliver.com
    ports:
      - "3002:3002"
    depends_on:
      - backend
    networks:
      - grs-network

  # Business PWA
  business-pwa:
    extends: app
    container_name: grs-business-pwa
    restart: unless-stopped
    environment:
      NODE_ENV: production
      SERVICE_NAME: business-pwa
      NEXT_PUBLIC_API_URL: https://api.grsdeliver.com
      NEXT_PUBLIC_WS_URL: wss://api.grsdeliver.com
    ports:
      - "3003:3003"
    depends_on:
      - backend
    networks:
      - grs-network

  # Driver PWA
  driver-pwa:
    extends: app
    container_name: grs-driver-pwa
    restart: unless-stopped
    environment:
      NODE_ENV: production
      SERVICE_NAME: driver-pwa
      NEXT_PUBLIC_API_URL: https://api.grsdeliver.com
      NEXT_PUBLIC_WS_URL: wss://api.grsdeliver.com
    ports:
      - "3004:3004"
    depends_on:
      - backend
    networks:
      - grs-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: grs-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available:/etc/nginx/sites-available
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - backend
      - public-pwa
      - admin-pwa
      - business-pwa
      - driver-pwa
    networks:
      - grs-network

volumes:
  mongodb_data:
  redis_data:

networks:
  grs-network:
    driver: bridge