version: '3.8'

services:
  # PostgreSQL database for development
  postgres:
    image: postgis/postgis:14-3.2
    container_name: delivery-uae-db
    environment:
      POSTGRES_DB: delivery_uae_dev
      POSTGRES_USER: delivery_user
      POSTGRES_PASSWORD: delivery_pass_2025
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./seeds.sql:/docker-entrypoint-initdb.d/02-seeds.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U delivery_user -d delivery_uae_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - delivery-network

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    container_name: delivery-uae-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass redis_pass_2025
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s 
      retries: 5
    restart: unless-stopped
    networks:
      - delivery-network

  # pgAdmin for database management (development only)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: delivery-uae-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@deliveryuae.com
      PGADMIN_DEFAULT_PASSWORD: admin_pass_2025
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - delivery-network
    profiles:
      - dev

  # Redis Commander for Redis management (development only)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: delivery-uae-redis-commander
    environment:
      REDIS_HOSTS: local:redis:6379:0:redis_pass_2025
      HTTP_USER: admin
      HTTP_PASSWORD: admin_pass_2025
    ports:
      - "8081:8081"
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - delivery-network
    profiles:
      - dev

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  delivery-network:
    driver: bridge
    name: delivery-uae-network